---
- name: Minecraft server setup
  hosts: all
  remote_user: ec2-user
  become: yes
  
  vars:
      ansible_ssh_private_key_file: ../mc_terra/minecraft_key.pem
      
  tasks:
    - name: Install Python
      yum:
        name: python3
        state: present

    - name: Update and Upgrade
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Java
      yum:
        name: java-22-amazon-corretto
        state: present

    - name: Create the directory for the Minecraft server
      file:
        path: /opt/minecraft
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Download JAR file
      get_url:
        url: https://piston-data.mojang.com/v1/objects/145ff0858209bcfc164859ba735d4199aafa1eea/server.jar
        dest: /opt/minecraft/server.jar
        mode: '0755'

    - name: Accept Minecraft EULA
      copy:
        content: "eula=true\n"
        dest: /opt/minecraft/eula.txt
        owner: root
        group: root
        mode: '0644'

    - name: Initalize system user for service
      user:
        name: minecraft
        system: yes
        create_home: no
        shell: /sbin/nologin

    - name: Set directory permissions for Minecraft
      file:
        path: /opt/minecraft
        state: directory
        owner: minecraft
        group: minecraft
        recurse: yes

    - name: Create Minecraft service
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=minecraft
          WorkingDirectory=/opt/minecraft
          ExecStart=/usr/bin/java -Xmx1024M -Xms1024M -jar /opt/minecraft/server.jar nogui
          SuccessExitStatus=143

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Start service
      systemd:
        name: minecraft
        state: started
        enabled: yes

    - name: Reload daemon
      systemd:
        daemon_reload: yes

    - name: Check server status
      command: systemctl status minecraft
      register: minecraft_service_status

    - name: Print Minecraft service status
      debug:
        var: minecraft_service_status.stdout
